typography_spectrum: 0.3408187174847774
color:
  brandStrength: 0.9573242627088865
  lightness: 0.8861738031990088
  saturation: 0.8518471112188948
  rhythmicContrast: 0.8085055609487256
  brandColors:
    - '#2C3E50'
    - '#E74C3C'
    - '#ECF0F1'
    - '#3498DB'
    - '#2980B9'
github: true
layout_spectrum: 0.1375525418292768
analytics:
  google: UA-90440402-1
author:
  name: Keeyan Ravanshid
  email: keeyan@kworldstandard.com
  url: 'http://keeyanravanshid.com'
name: Keeyan On The Grid
url: 'http://keeyanravanshid.com'
title: Ethan Keeyan Ravanshid.
content: []
description: LIVE FOR KNOWLEDGE.
