typography_spectrum: 0.1401652933564037
color:
  brandStrength: 0.17345945560373366
  lightness: 0.28175563691183925
  saturation: 0.06405299971811473
  rhythmicContrast: 0.7392332598101348
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
github: true
layout_spectrum: 0.8479840292129666
analytics:
  google: UA-90440402-1
author:
  name: Keeyan Ravanshid
  email: keeyan@kworldstandard.com
  url: 'http://keeyanravanshid.com'
name: Keeyan On The Grid
url: 'http://keeyanravanshid.com'
title: Ethan Keeyan Ravanshid.
content: []
description: LIVE FOR KNOWLEDGE.
